cockpit-project/cockpit-certificates

src/certificateList.jsx

If certificate is about to expire in 3-28 days, the unix epoch time
value was shown instead of remaining days until expiration.

Fix validity time in certificate header

---

test/check-application

Fixes a flake https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-1358-20201103-094522-45f76b30-fedora-33-skobyda-cockpit-certificates/log.html#8-2 in https://github.com/cockpit-project/bots/pull/1358

Fix fedora-33 testRequestCert flake

---

Makefile

This unblocks some Fedora image reorganization [1] which will in turn
make image preparations faster and more robust.
[1] https://github.com/cockpit-project/bots/pull/1407

Bump test/common dependency to 233

---

src/certificateActions.jsx
test/check-application

Before this change removing one certificate did not close the dialog
but showed a removal dialog for the next certificate until the `certs`
array was empty. Additionally this commit refactors common code into one
function.

Close dialog when certificate is removed

---

Makefile
cockpit-certificates.spec.in
packit.yml

This is necessary to comply with Fedora's packaging policy:
https://docs.fedoraproject.org/en-US/packaging-guidelines/JavaScript/
Include the node cache in the source rpm, unpack it into the main source
dir, and force a webpack rebuild in `%build`.
----
Tested the integration with cockpituous with:
```
$ export RELEASE_SOURCE="_release/source"
$ ~/upstream/cockpituous/release/release-source
$ ~/upstream/cockpituous/release/release-github
> Creating release draft: 2
> Uploading file: _release/source/cockpit-certificates-2.tar.gz
####################################################################################################################### 100.0%
> Uploading file: _release/source/cockpit-certificates-node-2.tar.xz
###################################################################### …
```

Rebuild webpack during RPM build

---

package.json

This depends on "coa", which recently got a trojan horse:
https://github.com/advisories/GHSA-73qr-pfmq-6rp8
As it's not being used at all, just drop it.

npm: Drop unused svgo dependency

---

src/emptyState.jsx

The expected indentation of self-closing tags became stricter with
current eslint-plugin-react versions.
---
See [this failure](https://logs.cockpit-project.org/logs/pull-2960-20220228-052734-fa4d4ff4-fedora-35-cockpit-project-cockpit-certificates/log.html)

src: Reformat EmptyState for eslint-plugin-react 7.29.x

---

packaging/cockpit-certificates.spec.in

According to the Fedora guidelines, nodejs-devel is needed for using
nodejs modules:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Node.js/#_buildrequires
Since this applies only on Fedora, and that nodejs-devel may not even
exist on other distros (e.g. CentOS 9 Stream), then limit the
nodejs-devel requirement only to Fedora, using nodejs unconditionally
everywhere.

spec: use nodejs-devel only on Fedora

---

packaging/cockpit-certificates.spec.in

Forwardport of https://github.com/cockpit-project/starter-kit/pull/575 to cockpit-certificates;
will be needed for https://bugzilla.redhat.com/show_bug.cgi?id=1969450

Fedora Packaging fixes v2

---

Makefile

This will fix tests on all Rawhide, Fedora 35 & 36.

Bump Cockpit API to include Python 3.11 compatibility fix

---

src/certificateActions.jsx

This was found by a update to one of the build tools:
ERROR in
/home/mvo/work/cockpit-certificates/src/certificateActions.jsx
83:50  error  Unknown property 'hasNoPaddingTop' found  react/no-unknown-property

Fix misplaced hasNoPaddingTop property

---

HACKING.md
Makefile
README.md
package.json
packaging/cockpit-certificates.spec.in
test/browser/browser.sh
webpack.config.js

Cockpit recently changed to an ESM build system [1]. Bump COCKPIT_REPO_COMMIT to that and follow suit.
This does not work with old node.js 10 any more which is still the default in RHEL 8. Install the newer version 16 instead.
[1] https://github.com/cockpit-project/cockpit/pull/18366
-----
Pretty much identical to https://github.com/cockpit-project/starter-kit/pull/625

build: Move to a webpack module, generalize bundler language/variable names

---

src/app.jsx
src/certificateActions.jsx
src/certificateList.jsx
src/emptyState.jsx
src/requestCertificate.jsx

Otherwise we rely on treeshaking mechanisms to remove unused code, thus making our bundle size more vulnerable to bundler's ability to drop dead code.

Use whole path in patternfly imports

---

test/check-application

Adding just 365 days to a current date is not a good way to a get a next year's date, since it doesn't account for leap years. This started to fail the tests, since next year (2024) is a leap year:
`wait_js_cond(ph_in_text("#certificate-0-validity","Auto-renews before 3/1/2024")): Uncaught (in promise) Error: actual text: Auto-renews before 3/2/2024, 7:30:34 am`
Fixes image-refresh: https://github.com/cockpit-project/bots/pull/4478

test: Account for leap years

---

packaging/cockpit-certificates.spec.in

This reverts commits 9734f58d5ad80f5d413dc5b7ef6294949978daeb and 097ea95f869db6deab6ef5aa5f1d94496c485cf5.
For the last couple of weeks, nodejs-devel has been uninstallable in COPR, as it has a different major version than nodejs. This was only introduced as a formality, not because we actually need it.

Revert "spec: use nodejs-devel only on Fedora", Revert "spec: Fix BuildRequires: to nodejs-devel"

---

.github/workflows/cockpit-lib-update.yml
.github/workflows/npm-update-pf.yml
.github/workflows/npm-update.yml

Like https://github.com/cockpit-project/starter-kit/pull/643 and https://github.com/cockpit-project/cockpit/pull/18668 . The newer ubuntu platform already got tested in cockpit and starter-kit, and most workflows here already had `permissions:`. 
I added `statuses: write`, as the PO workflows have it, too. I'm not sure that we really need it, but it's harmless enough.
I restricted the default token permissions to read-only now.

workflows: Update to ubuntu-latest, set explicit permissions

---

Makefile

The most recent Chromium 113 does not work any more with sizzle, tests were hanging as soon as they switched to a frame. The latest cockpit testlib applied a workaround [1]. As the latest Cockpit library also moved to PatternFly 5, but we haven't transitioned to that yet, switch to the (temporary) "290+chromium-sizzle" branch, which has that workaround backported.
[1] https://github.com/cockpit-project/cockpit/pull/18812

Update shared cockpit files for Chromium 113 fix

---

README.md

the `rm` command should remove cockpit-certificates instead of starter-kit

README: fix manual symlink remove

---

package.json

After the switch to esbuild nothing requires this.

package.json: drop cssnano-preset-lite

---

src/certificateActions.jsx

This was flaky causing certificate removal changes not to be noticed in CI as the certs state was not always updated in app.jsx

Correctly pass certificate changes to setState

---

pyproject.toml
test/check-application

These aren't unused, but discovered/enumerated by `unittest` or `pytest`.

lint: Ignore test functions in vulture
