src/app.jsx
src/certificateList.jsx
src/dbus.js
test/check-application

Subscribe to certmongerd dbus signal PropertiesChanged
Update the UI objects accordingly when signal is emitted

Subscribe to certmonger dbus signals

---

Makefile
src/app.jsx
test/check-application

There has been a lot of improvements since 208 and also due to new
privilege escalation this is need.

Bump up version of test/common

---

src/app.jsx
src/certificateActions.css
src/certificateActions.jsx
src/certificateList.jsx
src/dbus.js
test/check-application

It's important to note that removing certificate doesn't fully delete it. It just merely tells certmonger to stop tracking it. 
For example, if certificate file and key file are store somewhere on a system, removing certificate just tells certmonger to stop tracking it, but it does not delete the files nor does it revoke certificate by CA.
So I wondre what term is correct to use? Is "Remove" fine? Or perhaps we should use "Stop tracking" or something else? @andreasn @garrett

Implement certificate removal

---

src/certificateList.jsx
test/check-application

Autorenewal and stuck properties of certificate would not render if they are negative

Fix cert properties not showing

---

lib/cockpit-components-file-autocomplete.jsx
lib/cockpit-components-inline-notification.css
lib/cockpit-components-inline-notification.jsx
lib/cockpit-components-select.jsx
lib/page.scss
src/app.jsx
src/certificateList.jsx
src/dbus.js
src/requestCertificate.jsx
src/requestCertificate.scss
test/check-application

Draft of request a certificate dialog. 
This mainly deals with choosing a CA and choosing a certificate and key storage:
If NSSDB is chosen as storage type, a nickname needs to be specified to identify a certificate and key pair.
If file storage is chosen, user needs to specify a path where to storage a certificate.
They also need to specify a path to key which might or might not exist. If file exists, that file is used as key of certificate request. If file doesn't exist, certmonger will generate one and store it in given path.
@andreasn @garrett

Implemenent certificate request

---

lib/notifications.js
src/app.jsx
src/certificateList.css
src/certificateList.jsx
src/manifest.json
test/check-application

When certificate is about to expire (has less than 28 days until end of validity), show warning.
If certificate already expired, show error.
@garrett @andreasn

Warn user about expired or soon-to-expire certificates

---

src/certificateList.css
src/certificateList.jsx
src/dbus.js
src/states.js
test/check-application

Add checkbox which can change state of auto-renewal. Auto-renewal tells certmonger whetever to try to renew certificate once it gets close (28 days before) expiration date.
@garrett @andreasn

Redesign status and auto-renewal properties

---

src/certificateList.jsx
test/check-application

Let moment find the correct date format per language.

Don't use custom date-time formatting when settings the moment locale

---

src/certificateList.jsx
src/requestCertificate.jsx
test/check-application

Some wording improvements

---

Makefile
cockpit-certificates.spec.in
packit.yml

There is already release 1.
Make print-version was returning wrong version now.

packit: makefile: fix version

---

src/requestCertificate.jsx

The nickname field in the RequestCertificateModal is empty by default
and filled by asking the server for the hostname in componentDidMount.
As the tests are very fast, a certificate is created without a nickname
which fails the test. An empty nickname returns a certificate with round
brackets causing the grep/awk invocation to fail and the test to fail.
To not make the test have a race condition, the `request certificate`
button is now only shown when the hostname is available.

Handle race condition in testRequestCert

---

cockpit-certificates.spec.in

See https://bugzilla.redhat.com/show_bug.cgi?id=1969450#c8 ff.

Fedora packaging fixes

---

cockpit-certificates.spec.in
package.json
src/app.jsx
src/certificateList.jsx
src/requestCertificate.jsx
test/check-application

This module has been deprecated for a while.

Drop moment.js

---

src/certificateActions.jsx
src/certificateList.jsx
src/dbus.js
src/helpers.js
src/requestCertificate.jsx
test/check-application

Resubmitting a certificate will renew its expiration date. It's also the only point in the process when it's possible to amend some properties of an existing certificate such as DNS name, Principal name, Subject name.

Resubmit certificate

---

packit.yml
test/browser/browser.sh

Unbreak packit tests from last night's firefox regression.
Cherry-picked from starter-kit commit 9e162423eba.

fmf: Go back to firefox distro version

---

package.json

Stolen from @jelly's cockpit commit :)

node_modules: update chrome-remote-interface for chromium 111

---

test/check-application

Use magic shebang from Cockpit and change the tests to all be non-destructive.

Non destructive tests

---

src/certificateActions.jsx
test/check-application

Certificates is now :100: PF deprecated free

Use Cockpit's dropdown kebab

---

src/requestCertificate.jsx

One day we will switch this to a proper promise which does not support .done.

Stop using the jQuery like promise api

---

.github/workflows/tasks-container-update.yml

See https://github.com/cockpit-project/cockpit-certificates/actions/runs/8502955182/job/23287808583

workflows: Fix safe directory path in tasks-container-update.yml
